[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "WhatsAppBot"
authors = [{name = "Nanda Kishore", email = "pgsbssnk@gmail.com"}]
dynamic = ["version", "description"]
